// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC84puCjBNZLkq40oCaTSceQ9HHBiFNWGs',
    appId: '1:607123381687:web:060905b023369f6c5f5c32',
    messagingSenderId: '607123381687',
    projectId: 'luna-flow-45272',
    authDomain: 'luna-flow-45272.firebaseapp.com',
    storageBucket: 'luna-flow-45272.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlIg3ioXKEUaUVYBeV7B56WiUauEgDMHc',
    appId: '1:607123381687:android:b2636f0b3f6f9cf55f5c32',
    messagingSenderId: '607123381687',
    projectId: 'luna-flow-45272',
    storageBucket: 'luna-flow-45272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi7MzwJUCqSxkbl70wTdummq0hwkFsefI',
    appId: '1:607123381687:ios:367a95265ab153695f5c32',
    messagingSenderId: '607123381687',
    projectId: 'luna-flow-45272',
    storageBucket: 'luna-flow-45272.firebasestorage.app',
    iosBundleId: 'com.example.lunaflow.lunaflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi7MzwJUCqSxkbl70wTdummq0hwkFsefI',
    appId: '1:607123381687:ios:367a95265ab153695f5c32',
    messagingSenderId: '607123381687',
    projectId: 'luna-flow-45272',
    storageBucket: 'luna-flow-45272.firebasestorage.app',
    iosBundleId: 'com.example.lunaflow.lunaflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC84puCjBNZLkq40oCaTSceQ9HHBiFNWGs',
    appId: '1:607123381687:web:44e7c15c2ec2dffa5f5c32',
    messagingSenderId: '607123381687',
    projectId: 'luna-flow-45272',
    authDomain: 'luna-flow-45272.firebaseapp.com',
    storageBucket: 'luna-flow-45272.firebasestorage.app',
  );
}
